var text;
text = 'Hello World';
var text1;
text = 'Hello Worldaaaa';
console.log(text);
console.log(text1);
var in1;
in1 = "JOHN ZA 007";
console.log("1", in1.length);
console.log("2", in1.charAt(1));
console.log("3", in1[1]);
var str1 = "Hello";
var str2 = "World";
console.log("4", str1 + " " + str2);
